<!-- Pesquisar o endereço completo pelo CEP e auto preencher no formulario -->
<script type="text/javascript">
    function limpa_formulário_cep() {
        //Limpa valores do formulário de cep.
        document.getElementById('rua').value = ("");
        document.getElementById('bairro').value = ("");
        document.getElementById('cidade').value = ("");
        document.getElementById('uf').value = ("");
        //document.getElementById('ibge').value = ("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('rua').value = (conteudo.logradouro);
            document.getElementById('bairro').value = (conteudo.bairro);
            document.getElementById('cidade').value = (conteudo.localidade);
            document.getElementById('uf').value = (conteudo.uf);
            //document.getElementById('ibge').value = (conteudo.ibge);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }

    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('rua').value = "...";
                document.getElementById('bairro').value = "...";
                document.getElementById('cidade').value = "...";
                document.getElementById('uf').value = "...";
                //document.getElementById('ibge').value = "...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = '//viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };
</script>

<!-- Content Wrapper. Contains page content -->
<main class="container col-md-9 ml-sm-auto col-lg-10 px-4 mb-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Cadastro de Imoveis</h1>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="container-fluid">
                <form method="POST" action="/cadastra" enctype="multipart/form-data">
                    <!-- Grupo de três colunas  -->
                    <div class="row">
                        <div class="col-sm-5">
                            <!-- text input -->
                            <div class="form-group">
                                <label>Titulo:</label>
                                <input name="titulo" type="text" class="form-control" placeholder="Insira aqui o titulo do anuncio...">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Tipo do Imovel:</label>
                                <select name=" tipo_imovel" class="custom-select" required>
                                    <option disabled="disabled" selected="selected" value=""></option>
                                    <option value="Apartamento">Apartamento</option>
                                    <option value="Casa">Casa</option>

                                </select>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label>Destinado á:</label>
                                <select name=" tipo_contrato" class="custom-select" required>
                                    <option disabled="disabled" selected="selected" value=""></option>
                                    <option value="Aluguel">Aluguel</option>
                                    <option value="Venda">Venda</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!-- FIM  -->


                    <!-- Grupo de Endereço 3 colunas  -->
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Valor:</label>
                                <input name="valor" id="valor" type="text" class="valor form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <!-- text input -->
                            <div class="form-group">
                                <label>CEP:</label>
                                <input name="cep" id="cep" type="text" class="form-control" placeholder="" onblur="pesquisacep(this.value);">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group">
                                <label>Rua:</label>
                                <input name="rua" id="rua" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <label>Nº:</label>
                                <input name="numero_end" id="rua" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                    </div>
                    <!-- FIM  -->
                    <!-- Grupo de Endereço 3 colunas  -->
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Bairro:</label>
                                <input name="bairro" id="bairro" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <!-- text input -->
                            <div class="form-group">
                                <label>Cidade:</label>
                                <input name="cidade" id="cidade" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-sm-1">
                            <div class="form-group">
                                <label>UF:</label>
                                <input name="estado" id="uf" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label>Complemento:</label>
                                <input name="complemento_end" type="text" class="form-control" placeholder="">
                            </div>
                        </div>
                    </div>
                    <!-- FIM  -->
                    <!-- Grupo de duas colunas  -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Descrição:</label>
                                <textarea name="descricao" class="form-control" rows="8" placeholder="Insira aqui os detalhes do imovel..."></textarea>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="mb-3">
                            <div class="form-group">
                                <label>Imagem:</label>
                                <input type="file" name="imagem" class="form-control-file">
                            </div>
                        </div>

                    </div>
                    <button type="submit" class="btn btn-dark">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>
</main>
<script type="text/javascript">
    $(document).ready(function() {
        $("#valor").maskMoney();
    });
</script>